version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: RevoDB
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: revodev
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  pg-data:
